In [3]:
import numpy as np
from matplotlib import pyplot as plt

In [8]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
a[0]

1

In [14]:
a[:]

array([1, 2, 3])

In [17]:
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [18]:
a[1:3]

array([2, 3])

In [46]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
b[1]

array([4, 5, 6])

In [30]:
b[0,0:2]

array([1, 2])

In [32]:
b[:,1]

array([2, 5])

In [39]:
a.shape

(3,)

In [47]:
b.shape

(2, 3)

In [52]:
c = np.random.rand(3,3,3)

In [53]:
c.shape

(3, 3, 3)

In [34]:
b = np.array([[1,2,3],[4,5,6],[1,2,3]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [55]:
c[:,0,:]

array([[0.48012845, 0.07994983, 0.1934657 ],
       [0.62076487, 0.96799358, 0.55863439],
       [0.1157555 , 0.93927796, 0.56328746]])

In [48]:
c[0,0,0]

0.9097499641743798

In [51]:
c[:,:,0]

array([[0.90974996, 0.44914056],
       [0.73750398, 0.011404  ]])